#!/bin/bash


# -tls1_3
# -no_ssl3 -no_tls1 -no_tls1_1 -no_tls1_2
# -bugs
# -msg 
/usr/local/opt/openssl/bin/openssl s_server \
    -certform PEM -cert /Users/luozijun/Project/tls/keys/server.crt \
    -keyform PEM -key /Users/luozijun/Project/tls/keys/server.key \
    -port 443 \
    -alpn "h2,dot" \
    -state \
    -tls1_3 \
    -debug -tlsextdebug -security_debug \
    -verify_hostname "localhost" \
    -verify_ip "127.0.0.1" \
